---
"cro": 1
"endpoints": 
  - 
    "host-env": "WEBSITE_HOST"
    "id": "http"
    "name": "HTTP"
    "port-env": "WEBSITE_PORT"
    "protocol": "http"
"entrypoint": "service.raku"
"env":  []
"id": "Elucid8"
"links":  []
"name": "Elucid8"
...